name: event_finder_fixed
description: "A fully functional event discovery Flutter app."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  add_2_calendar: ^3.0.1
  curved_navigation_bar: ^1.0.3
 


  # State management
  provider: ^6.1.1
  # Firebase core features
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0
  

  # UI & UX
  lottie: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^17.0.0
  google_maps_flutter: ^2.6.0
  shared_preferences: ^2.5.3
  share_plus: ^7.2.1
  intl: ^0.19.0

  # Utilities
  url_launcher: ^6.2.5
  http: ^0.13.6
  image_picker: ^1.1.0
  path_provider: ^2.1.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/event_logo.png
    - assets/animations/onboarding_discover.png
    - assets/animations/onboarding_save.png
    - assets/animations/onboarding_notify.png
