// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqGCXdd5E-K644_UR47Ri_AW1MPEfVREk',
    appId: '1:1036687973946:web:c9377ec2f7aa4edb7f5f03',
    messagingSenderId: '1036687973946',
    projectId: 'event-finder-fabd7',
    authDomain: 'event-finder-fabd7.firebaseapp.com',
    databaseURL: 'https://event-finder-fabd7-default-rtdb.firebaseio.com',
    storageBucket: 'event-finder-fabd7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYHM-jOB0dZXPxLdH5Q0-5Xed9mfxXufc',
    appId: '1:1036687973946:android:16dfda275ace7b527f5f03',
    messagingSenderId: '1036687973946',
    projectId: 'event-finder-fabd7',
    databaseURL: 'https://event-finder-fabd7-default-rtdb.firebaseio.com',
    storageBucket: 'event-finder-fabd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5qVHUx2GuFUEqcLMzkImbLvuclungaw',
    appId: '1:1036687973946:ios:e41f1fa0cc775e427f5f03',
    messagingSenderId: '1036687973946',
    projectId: 'event-finder-fabd7',
    databaseURL: 'https://event-finder-fabd7-default-rtdb.firebaseio.com',
    storageBucket: 'event-finder-fabd7.firebasestorage.app',
    iosBundleId: 'com.example.eventFinderFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU5qVHUx2GuFUEqcLMzkImbLvuclungaw',
    appId: '1:1036687973946:ios:e41f1fa0cc775e427f5f03',
    messagingSenderId: '1036687973946',
    projectId: 'event-finder-fabd7',
    databaseURL: 'https://event-finder-fabd7-default-rtdb.firebaseio.com',
    storageBucket: 'event-finder-fabd7.firebasestorage.app',
    iosBundleId: 'com.example.eventFinderFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqGCXdd5E-K644_UR47Ri_AW1MPEfVREk',
    appId: '1:1036687973946:web:e07172c3e47949257f5f03',
    messagingSenderId: '1036687973946',
    projectId: 'event-finder-fabd7',
    authDomain: 'event-finder-fabd7.firebaseapp.com',
    databaseURL: 'https://event-finder-fabd7-default-rtdb.firebaseio.com',
    storageBucket: 'event-finder-fabd7.firebasestorage.app',
  );
}
